"use client"
import React, { useEffect, useRef, useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "./index.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [activeMenu, setActiveMenu] = useState<string | null>(null);
  const navRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (!navRef.current) return;
      if (activeMenu && !navRef.current.contains(event.target as Node)) {
        setActiveMenu(null);
      }
    };

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setActiveMenu(null);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("keydown", handleEscape);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleEscape);
    };
  }, [activeMenu]);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <div className="relative">
        <nav ref={navRef} className="sticky top-0 z-40 bg-white shadow-sm">
          <div className="bg-black text-white p-1">
            <p className="text-center pt-1">
              Get access lauches and oMera. <Link className="underline" href="#">Sign in for trota</Link>➡️
            </p>
            <p className="text-end pr-1 -mt-5 hidden md:block">NIG</p>
          </div>
          <div id="navs" className="flex justify-around items-center pt-2 pb-2 relative">
            <div className="text-black pr-3 flex">
              <button className="mr-2 text-xs md:text-sm lg:text-sm md:mr-5 lg:mr-10" onClick={() => setActiveMenu(activeMenu === 'Women' ? null : 'Women')}>Women</button>
              <button className="mr-2 text-xs md:text-sm lg:text-sm md:mr-5 lg:mr-10" onClick={() => setActiveMenu(activeMenu === 'Man' ? null : 'Man')}>Man</button>
              <Link href="/about" className="mr-2 text-xs md:text-sm lg:text-sm md:mr-5 lg:mr-10" onClick={() => setActiveMenu(null)}>
                About
              </Link>
              <button className="mr-2 text-xs md:text-sm lg:text-sm md:mr-5 lg:mr-10" onClick={() => setActiveMenu(activeMenu === 'Evergreen shorts' ? null : 'Evergreen shorts')}>Evergreen shorts</button>
            </div>
            <div className="text-black text-center text-3xl mr-8 md:-ml-32 lg:-ml-64">
              <span className="font-semibold text-xs md:text-sm lg:text-3xl">EVERLANE</span>
            </div>
            <div className="text-xs md:text-sm lg:text-xl">
              <span className="mr-5">🔍</span>
              <span className="mr-5">👤</span>
              <span className="mr-5">🛒</span>
            </div>
          </div>
          {activeMenu && (
            <div className="absolute left-0 right-0 top-full bg-white shadow-2xl border-t border-black z-50">
              <div className="mx-auto max-w-6xl px-6 py-8">
                <div className="mb-4 text-right text-xs text-gray-500">Press ESC to close</div>
                {activeMenu === 'Man' ? (
                  <div className="grid gap-8 lg:grid-cols-4">
                    <div>
                      <h2 className="mb-4 text-xl font-bold">Men</h2>
                      <ul className="space-y-2 text-sm text-gray-700">
                        <li className="cursor-pointer hover:underline">New Arrivals</li>
                        <li className="cursor-pointer hover:underline">Shirts & Tops</li>
                        <li className="cursor-pointer hover:underline">Pants & Jeans</li>
                        <li className="cursor-pointer hover:underline">Outerwear</li>
                        <li className="cursor-pointer hover:underline">Accessories</li>
                      </ul>
                    </div>
                    <div>
                      <h2 className="mb-4 text-xl font-bold">Featured</h2>
                      <ul className="space-y-2 text-sm text-gray-700">
                        <li className="cursor-pointer hover:underline">Holiday Outfit Edit</li>
                        <li className="cursor-pointer hover:underline">Giftable Sweaters</li>
                        <li className="cursor-pointer hover:underline">Uniform & Capsule</li>
                        <li className="cursor-pointer hover:underline">Performance Layering</li>
                        <li className="cursor-pointer hover:underline">Under $100</li>
                      </ul>
                    </div>
                    <div className="lg:col-span-2 grid gap-4 sm:grid-cols-2">
                      <div className="bg-black text-white p-6 flex items-center justify-center">
                        <div className="text-center">
                          <p className="font-bold">The Holiday</p>
                          <p className="text-sm">Outfit Edit</p>
                        </div>
                      </div>
                      <div className="bg-gray-100 p-6 flex items-center justify-center">
                        <p className="text-sm font-semibold text-center">Giftable Sweaters</p>
                      </div>
                    </div>
                  </div>
                ) : activeMenu === 'About' ? (
                  <div className="grid gap-8 lg:grid-cols-2 items-center">
                    <div>
                      <h2 className="mb-4 text-2xl font-bold">About Everlane</h2>
                      <p className="mb-4 text-sm text-gray-700">
                        We champion better basics with thoughtful design and a commitment to transparency.
                      </p>
                      <p className="mb-6 text-sm text-gray-700">
                        See how our products are made, with premium materials, honest pricing, and real-world comfort.
                      </p>
                      <button className="bg-black text-white px-5 py-3 text-sm font-semibold">Learn More</button>
                    </div>
                    <div className="overflow-hidden rounded-lg bg-gray-100">
                      <img src="/person1.jpg" alt="About Everlane" className="h-full w-full object-cover" />
                    </div>
                  </div>
                ) : (
                  <div className="grid gap-8 lg:grid-cols-2 items-center">
                    <div>
                      <h2 className="mb-4 text-xl font-bold">Evergreen shorts</h2>
                      <p className="mb-4 text-sm text-gray-700">
                        Explore our best-selling shorts with clean lines, durable fabrics, and everyday comfort.
                      </p>
                      <ul className="space-y-2 text-sm text-gray-700">
                        <li className="cursor-pointer hover:underline">Classic Fit</li>
                        <li className="cursor-pointer hover:underline">Performance</li>
                        <li className="cursor-pointer hover:underline">New Colors</li>
                      </ul>
                    </div>
                    <div className="overflow-hidden rounded-lg bg-gray-100">
                      <img src="/person2.jpg" alt="Evergreen shorts" className="h-full w-full object-cover" />
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
          <hr />
        </nav>
      </div>
      <body className="min-h-full flex flex-col bg-white">{children}</body>
    </html>
  );
}
